### PR TITLE
Update to OpenSSL 1.0.2n and improve the entropyRT() implementation. 

### PR DESCRIPTION
**Pull request by MouriNaruto**
- OpenSSL update to 1.0.2n (The latest stable version of 1.0.2 series.)
- Improve the entropyRT() implementation. 
  - Use IBufferByteAccess instead of Platform::Array to reduce overhead.

Mouri

### CODE REVIEW

**Comment by noloader** [comment]
> Use IBufferByteAccess instead of Platform::Array to reduce overhead.

Windows really needs to provide a native method to get a seed on *all* platforms.

The Botan and Crypto++ library disable Random Number Generators because they are not managed libraries. They cannot use `RNGCryptoServiceProvider`, `IBufferByteAccess`, `CryptographicBuffer.GenerateRandom`, and friends.

**Comment by MouriNaruto** [comment]
Windows Runtime is native framework based on COM.
So, you can use Windows Runtime interfaces on native libraries.

PS: OpenSSL is a native library. So you should trust my words.

@noloader

**Comment by khouzam** [comment]
Hi @MouriNaruto,

Thanks for the update, would you mind splitting this into 2 pull requests? One to update to 1.0.2.n and another one for the entropy? Or I can do the update to 1.0.2n and then you can make the PR to add the entropy improvements.

Thanks.

**Comment by MouriNaruto** [comment]
Thank you.
I don't mind, I'll do it as soon as possible.

**Comment by MouriNaruto** [comment]
Hi, @khouzam 

https://github.com/Microsoft/openssl/pull/51

It is the pull request that only update to OpenSSL 1.0.2n.
I will create the second pull request as soon as possible after you merged that.

**Comment by khouzam** [comment]
Thank you for the code. I've merged it into the OpenSSL_1_0_2_WinRT-stable branch.

**Comment by MouriNaruto** [comment]
Thank you for your help. This is my first pull request in other people's repository.

**Pull request closed without merging**
